# Generated by Django 3.2.7 on 2021-09-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='href',
            field=models.CharField(default='0000000', max_length=30),
        ),
        migrations.AddField(
            model_name='path',
            name='icon',
            field=models.CharField(default='0000000', max_length=30),
        ),
        migrations.AddField(
            model_name='path',
            name='title',
            field=models.CharField(default='0000000', max_length=50),
        ),
    ]
