# Generated by Django 3.2.7 on 2021-09-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210927_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='href',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='path',
            name='icon',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='path',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
