# Generated by Django 3.2.7 on 2021-10-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210928_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='english_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='path',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
