# Generated by Django 3.2.7 on 2021-09-14 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('spanish_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UserReviewState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TypeInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_usd', models.DecimalField(decimal_places=0, max_digits=3)),
                ('name', models.CharField(max_length=40)),
                ('spanish_name', models.CharField(max_length=40)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profile_api.usertype')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('document_number', models.CharField(blank=True, max_length=12, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('mobile', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('job_title', models.CharField(blank=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('document_image', models.ImageField(null=True, upload_to='docs/identification')),
                ('other_document_image', models.ImageField(null=True, upload_to='docs/other')),
                ('token_id', models.CharField(blank=True, max_length=25, null=True)),
                ('publicity', models.BooleanField(blank=True, null=True)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profile_api.documenttype')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
                ('user_review_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile_api.userreviewstate')),
                ('user_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile_api.usertype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
