# Generated by Django 3.2.7 on 2021-09-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0002_alter_userprofile_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='num_digits',
            field=models.IntegerField(default=8),
        ),
    ]
