# Generated by Django 3.2.7 on 2021-09-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0003_documenttype_num_digits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeinscription',
            name='payment_usd',
            field=models.IntegerField(),
        ),
    ]
