# Generated by Django 3.2.7 on 2021-09-15 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0004_alter_typeinscription_payment_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='document_image',
            field=models.ImageField(blank=True, null=True, upload_to='docs/identification'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='other_document_image',
            field=models.ImageField(blank=True, null=True, upload_to='docs/other'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile_api.usertype'),
        ),
    ]
