# Generated by Django 3.2.7 on 2021-09-15 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profile_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0006_auto_20210914_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=30)),
                ('max_num_users_inscribed', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='feria3d',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='document_image',
            field=models.ImageField(blank=True, null=True, upload_to=profile_api.models.UserProfile.document_directory_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='other_document_image',
            field=models.ImageField(blank=True, null=True, upload_to=profile_api.models.UserProfile.other_document_directory_path),
        ),
        migrations.CreateModel(
            name='CorporateUserInscribed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profile_api.corporategroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='corporategroup',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
