# Generated by Django 3.2.7 on 2021-09-15 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0007_auto_20210915_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='token_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(max_length=25)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profile_api.typeinscription')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
