# Generated by Django 3.2.7 on 2021-09-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0008_auto_20210915_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='document_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
