# Generated by Django 3.2.7 on 2021-09-17 20:16

from django.db import migrations, models
import profile_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0009_alter_userprofile_document_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='document_image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='other_document_image',
        ),
        migrations.AddField(
            model_name='corporategroup',
            name='token_id',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='evidence_image',
            field=models.FileField(blank=True, null=True, upload_to=profile_api.models.UserProfile.document_directory_path),
        ),
    ]
