# Generated by Django 3.2.7 on 2021-09-20 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0010_auto_20210917_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporategroup',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='corporate_group', to=settings.AUTH_USER_MODEL),
        ),
    ]
