# Generated by Django 3.2.7 on 2021-09-21 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0011_alter_corporategroup_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateuserinscribed',
            name='corporate_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='profile_api.corporategroup'),
        ),
    ]
