# Generated by Django 3.2.7 on 2021-09-21 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0012_alter_corporateuserinscribed_corporate_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporategroup',
            name='token_id',
        ),
        migrations.CreateModel(
            name='CorporateGroupPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=25)),
                ('number_participants', models.IntegerField()),
                ('corporate_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='profile_api.corporategroup')),
            ],
        ),
    ]
