# Generated by Django 3.2.7 on 2021-09-21 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0013_auto_20210921_1130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CorporateGroupPayments',
            new_name='CorporateGroupPayment',
        ),
    ]
