# Generated by Django 3.2.7 on 2021-09-22 19:31

from django.db import migrations, models
import profile_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0014_rename_corporategrouppayments_corporategrouppayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to=profile_api.models.UserProfile.document_directory_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='evidence_image',
            field=models.FileField(blank=True, null=True, upload_to=profile_api.models.UserProfile.other_document_directory_path),
        ),
    ]
