# Generated by Django 3.2.7 on 2021-09-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0017_corporategrouppayment_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporategrouppayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
