# Generated by Django 3.2.7 on 2021-09-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0019_alter_corporategrouppayment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporategrouppayment',
            name='currency',
            field=models.CharField(default='PEN', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corporategrouppayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
