# Generated by Django 3.2.7 on 2021-09-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0020_auto_20210929_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporategrouppayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
