# Generated by Django 3.2.7 on 2021-10-07 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0023_alter_corporateuserinscribed_corporate_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporategroup',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_group', to=settings.AUTH_USER_MODEL),
        ),
    ]
