# Generated by Django 3.2.7 on 2021-10-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0024_alter_corporategroup_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
