# Generated by Django 3.2.7 on 2021-09-30 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fair3D.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r', models.IntegerField()),
                ('g', models.IntegerField()),
                ('b', models.IntegerField()),
                ('material', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url_facebook', models.URLField(null=True)),
                ('url_twitter', models.URLField(null=True)),
                ('url_linkedin', models.URLField(null=True)),
                ('url_web_page', models.URLField(null=True)),
                ('url_video', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Whatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('stand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fair3D.staff')),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='stand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fair3D.stand'),
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=fair3D.models.Pdf.document_directory_path)),
                ('description', models.CharField(max_length=100)),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fair3D.stand')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=fair3D.models.Image.document_directory_path)),
                ('caption', models.CharField(max_length=100)),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fair3D.stand')),
            ],
        ),
        migrations.CreateModel(
            name='Excel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=fair3D.models.Excel.document_directory_path)),
                ('description', models.CharField(max_length=100)),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fair3D.stand')),
            ],
        ),
        migrations.CreateModel(
            name='Calendify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('stand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fair3D.staff')),
            ],
        ),
    ]
