# Generated by Django 3.2.7 on 2021-09-30 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fair3D', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='stand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fair3D.stand'),
            preserve_default=False,
        ),
    ]
