# Generated by Django 3.2.7 on 2021-09-30 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fair3D', '0002_color_stand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendify',
            name='stand',
        ),
        migrations.RemoveField(
            model_name='whatsapp',
            name='stand',
        ),
        migrations.AddField(
            model_name='calendify',
            name='staff',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='calendify', to='fair3D.staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whatsapp',
            name='staff',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp', to='fair3D.staff'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='color',
            name='stand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='fair3D.stand'),
        ),
        migrations.AlterField(
            model_name='excel',
            name='stand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excels', to='fair3D.stand'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='stand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='fair3D.stand'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='stand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='fair3D.stand'),
        ),
    ]
