# Generated by Django 3.2.7 on 2021-10-04 15:38

from django.db import migrations, models
import django.db.models.deletion
import fair3D.models


class Migration(migrations.Migration):

    dependencies = [
        ('fair3D', '0004_alter_image_stand'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1)),
                ('area', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='stand',
            name='type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
                ('link', models.URLField()),
                ('stand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='showroom', to='fair3D.stand')),
            ],
        ),
        migrations.CreateModel(
            name='Resource3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.FileField(upload_to=fair3D.models.Resource3D.document_directory_path)),
                ('description', models.CharField(max_length=100, null=True)),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources_3d', to='fair3D.stand')),
            ],
        ),
    ]
