# Generated by Django 3.2.7 on 2021-10-05 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0023_alter_corporateuserinscribed_corporate_group'),
        ('fair3D', '0007_stand_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='stand',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stand', to='profile_api.corporategroup'),
        ),
    ]
