# Generated by Django 3.2.7 on 2021-10-05 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fair3D', '0008_stand_stand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stand',
            old_name='stand',
            new_name='corporate_group',
        ),
    ]
