# Generated by Django 3.2.7 on 2021-10-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fair3D', '0009_rename_stand_stand_corporate_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standtype',
            name='name',
            field=models.CharField(max_length=6),
        ),
    ]
