# Generated by Django 3.2.7 on 2021-10-05 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fair3D', '0010_alter_standtype_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stand',
            name='corporate_group',
        ),
    ]
