# Generated by Django 3.2.7 on 2021-10-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fair3D', '0012_auto_20211005_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
